---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  config: "../../.yamllint"
platforms:
  - name: maas-single-1604
    image: Ubuntu 16.04 Xenial Xerus
    flavor: 2C-4GB-50GB
    network: Default network
    groups:
      - maas
    children:
      - maas_region_controller
      - maas_rack_controller  

  - name: maas-single-1804
    image: Ubuntu 18.04 Bionic Beaver
    flavor: 2C-4GB-50GB
    ssh_user: ubuntu
    sshuser: ubuntu
    network: Default network
    groups:
      - maas
    children:
      - maas_region_controller
      - maas_rack_controller
    
provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
